# AI提供商配置
providers:
  gpt4:  # 提供商标识符，用户自定义
    type: openai  # 提供商类型，使用预设的处理方法
    api_key: your_gpt4_api_key
    base_url: https://api.openai.com/v1
    model: gpt-4-turbo-preview
    max_tokens: 2000

  openai-azure:  # Azure OpenAI示例
    type: openai
    api_key: your_azure_api_key
    base_url: https://your-resource.openai.azure.com
    model: gpt-35-turbo
    max_tokens: 2000

  claude:
    type: anthropic
    api_key: your_anthropic_api_key
    model: claude-3-sonnet
    max_tokens: 2000

  local-deepseek-r1-14b:
    type: ollama
    base_url: http://localhost:11434
    model: deepseek-r1:14b
    max_tokens: 2000

  deepseek-api:
    type: openai  # DeepSeek 使用 OpenAI 兼容接口
    api_key: your_deepseek_api_key
    base_url: https://api.deepseek.com/chat/completions
    model: deepseek-chat
    max_tokens: 2000

# 提供商分组配置
groups:
  local-models:  # 本地部署模型组
    - local-deepseek-r1-14b
  cloud-services:  # 云服务提供商组
    - gpt4
    - claude
    - openai-azure
  deepseek-all:  # DeepSeek 全系列
    - deepseek-api
    - local-deepseek-r1-14b

# 默认的提供商优先级顺序（支持组名和提供商名混合）
priority:
  - local-models    # 优先尝试本地模型
  - deepseek-all    # 其次尝试DeepSeek系列
  - cloud-services  # 最后使用其他云服务
