version: '3.8'

services:
  main:
    build: .
    container_name: ars
    ports:
      - "8000:8000"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=DEBUG
      - LOG_DIR=/app/logs
      - LOG_FILE_SIZE=100M
      - LOG_BACKUP_COUNT=10
    restart: unless-stopped
